# Generated by Django 2.1.4 on 2018-12-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentimentmodel',
            old_name='sentence',
            new_name='Sentence',
        ),
    ]
